# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c59346779e70ae35c69bf3d936246b728195c20c16eda18db7bd3c96f2f3e555417fbbd6327fdcfcc1efef47a9ccad2195c50359ebe4b87334cf4135b1ce4b2

test:
  secret_key_base: ac96c49fc662fa851cc60747c8a9b2b8cd8cda83abf59602df10dce2f1fd5cb091f002b3d16e4daefdb8acfc47fbc629ccac06fbf4f734b0977aab7b878f4c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
